kubeEtcd:
  enabled: false

endpointController:
  enabled: true
  kubeServices: false
  etcdService: false
  windowsExporterService: true
  nodeSelector:
    kubernetes.io/os: linux

kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: linux

prometheus-operator:
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    nodeSelector:
      kubernetes.io/os: linux
    tlsProxy:
      enabled: false

prometheus-node-exporter:
  nodeSelector:
    kubernetes.io/os: linux

prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/os: linux
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: default
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/os: linux
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: default
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - receiver: 'null'
        match:
          alertname: "Watchdog"
      - receiver: 'null'
        match_re:
          alertname: 'KubeControllerManagerDown|KubeProxyDown|KubeSchedulerDown'
      - receiver: 'mypager'
        match_re:
          alertname: 'KubePodCrashLooping|KubePodNotReady|KubeContainerWaiting'
    receivers:
    - name: 'null'
    - name: 'mypager'


grafana:
  nodeSelector:
    kubernetes.io/os: linux
  # persistence:
  #   type: pvc
  #   enabled: true
  adminPassword: To1Bp37ZYKuz353uYhot

vector-agent:
  enabled: false

promtail:
  enabled: false

otel-operator:
  enabled: false
