name: Release

on:
  push:
    tags:
      - v*

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v2
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-SqlServer-PSScriptAnalyzer
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az, xPSDesiredStateConfiguration
      - name: Package Extension
        shell: pwsh
        run: |
          Publish-AzVMDscConfiguration ./pwe-vmss-extension.zip/ConfigureWindowsExporter.ps1 -OutputArchivePath ./pwe-vmss-extension.zip
      - name: Create release
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release create ${{ steps.vars.outputs.tag }}
          gh release upload ${{ steps.vars.outputs.tag }} ./pwe-vmss-extension.zip
