name: Release

on:
  push:
    tags:
      - v*

jobs:
  cd:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Retrieve version
        shell: bash
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-WindowsExporterExtension
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Compute
          Install-Module xPSDesiredStateConfiguration
      - name: Package Extension
        shell: pwsh
        run: |
          Publish-AzVMDscConfiguration ./pwe-vmss-extension/ConfigureWindowsExporter.ps1 -OutputArchivePath ./pwe-vmss-extension.zip
      - name: Create release
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release create ${{ steps.vars.outputs.tag }}
          gh release upload ${{ steps.vars.outputs.tag }} ./pwe-vmss-extension.zip
